import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PayslipPdfService {
  static Future<void> generateAndPreview(Map<String, dynamic> payslip, int year, int month, {String lang = 'en'}) async {
    final pdf = _buildPdf(payslip, year, month, lang: lang);
    await Printing.layoutPdf(onLayout: (format) => pdf.save());
  }

  static Future<void> sharePdf(Map<String, dynamic> payslip, int year, int month, {String lang = 'en'}) async {
    final pdf = _buildPdf(payslip, year, month, lang: lang);
    final bytes = await pdf.save();
    final monthName = DateFormat('MMMM_yyyy').format(DateTime(year, month));
    await Printing.sharePdf(bytes: bytes, filename: 'Payslip_$monthName.pdf');
  }

  // Bilingual labels
  static Map<String, String> _l(String lang) => lang == 'mm' ? {
    'payslip': 'လစာရွှင်း',
    'employee_info': 'ဝန်ထမ်းအချက်အလက်',
    'payroll_info': 'လစာအချက်အလက်',
    'name': 'အမည်',
    'emp_code': 'ဝန်ထမ်းကုဒ်',
    'department': 'ဌာန',
    'position': 'ရာထူး',
    'phone': 'ဖုန်း',
    'nrc': 'မှတ်ပုံတင်',
    'pay_period': 'လစာလ',
    'status': 'အခြေအနေ',
    'bank': 'ဘဏ်',
    'bank_acc': 'ဘဏ်အကောင့်',
    'attendance': 'တက်ရောက်မှု',
    'working_days': 'အလုပ်ရက်',
    'present': 'တက်ရက်',
    'absent': 'ပျက်ရက်',
    'late': 'နောက်ကျ',
    'on_leave': 'ခွင့်',
    'earnings': 'ရရှိငွေ',
    'basic_salary': 'အခြေခံလစာ',
    'transport': 'သွားလာစရိတ်',
    'meal': 'ထမင်းစရိတ်',
    'phone_allowance': 'ဖုန်းစရိတ်',
    'housing': 'အိမ်ခန်းစရိတ်',
    'other_allowance': 'အခြားစရိတ်',
    'position_allowance': 'ရာထူးစရိတ်',
    'overtime': 'အချိန်ပိုကြေး',
    'ot_hours': 'အချိန်ပိုနာရီ',
    'attendance_bonus': 'ရက်မှန်ကြေး',
    'bonus': 'ဆုကြေး',
    'performance_bonus': 'စွမ်းဆောင်ရည်ဆုကြေး',
    'incentive': 'မက်လုံး',
    'commission': 'ကော်မရှင်',
    'other_earnings': 'အခြားရရှိငွေ',
    'total_earnings': 'စုစုပေါင်းဝင်ငွေ',
    'deductions': 'နုတ်ယူငွေ',
    'ssb': 'လူမှုဖူလုံရေး (SSB)',
    'income_tax': 'ဝင်ငွေခွန်',
    'advance': 'ကြိုတင်ထုတ်ငွေ',
    'absent_ded': 'ပျက်ကွက်နုတ်ငွေ',
    'unpaid_leave_ded': 'ခွင့်မဲ့နုတ်ငွေ',
    'late_ded': 'နောက်ကျနုတ်ငွေ',
    'loan_ded': 'ချေးငွေပြန်ဆပ်',
    'insurance_ded': 'အာမခံ',
    'uniform_ded': 'ယူနီဖောင်းနုတ်ငွေ',
    'other_deductions': 'အခြားနုတ်ယူငွေ',
    'total_deductions': 'စုစုပေါင်းနုတ်ယူငွေ',
    'net_salary': 'လက်ခံရရှိငွေ',
    'generated_by': 'Easy HR မှ ထုတ်ပေးသည်',
    'confidential': 'ဤလစာရွှင်းတမ်းသည် ကွန်ပျူတာမှ ထုတ်ပေးခြင်းဖြစ်ပြီး လက်မှတ်မလိုအပ်ပါ။ လျှို့ဝှက်စာရွက်ဖြစ်သည်။',
    'date': 'ရက်စွဲ',
    'description': 'အကြောင်းအရာ',
    'amount': 'ပမာဏ',
  } : {
    'payslip': 'Payslip',
    'employee_info': 'EMPLOYEE INFO',
    'payroll_info': 'PAYROLL INFO',
    'name': 'Name',
    'emp_code': 'Employee Code',
    'department': 'Department',
    'position': 'Position',
    'phone': 'Phone',
    'nrc': 'NRC',
    'pay_period': 'Pay Period',
    'status': 'Status',
    'bank': 'Bank',
    'bank_acc': 'Bank Account',
    'attendance': 'ATTENDANCE SUMMARY',
    'working_days': 'Working Days',
    'present': 'Present',
    'absent': 'Absent',
    'late': 'Late',
    'on_leave': 'On Leave',
    'earnings': 'EARNINGS',
    'basic_salary': 'Basic Monthly Salary',
    'transport': 'Transport Allowance',
    'meal': 'Meal Allowance',
    'phone_allowance': 'Phone Allowance',
    'housing': 'Housing Allowance',
    'other_allowance': 'Other Allowance',
    'position_allowance': 'Position Allowance',
    'overtime': 'Overtime Pay',
    'ot_hours': 'OT Hours',
    'attendance_bonus': 'Attendance Bonus',
    'bonus': 'Bonus',
    'performance_bonus': 'Performance Bonus',
    'incentive': 'Incentive',
    'commission': 'Commission',
    'other_earnings': 'Other Earnings',
    'total_earnings': 'Gross Salary',
    'deductions': 'DEDUCTIONS',
    'ssb': 'Social Security Board (SSB)',
    'income_tax': 'Income Tax',
    'advance': 'Salary Advance Deduction',
    'absent_ded': 'Absent Deduction',
    'unpaid_leave_ded': 'Unpaid Leave Deduction',
    'late_ded': 'Late Deduction',
    'loan_ded': 'Loan Repayment',
    'insurance_ded': 'Insurance',
    'uniform_ded': 'Uniform Deduction',
    'other_deductions': 'Other Deductions',
    'total_deductions': 'Total Deductions',
    'net_salary': 'Net Pay',
    'generated_by': 'Generated by Easy HR',
    'confidential': 'This is a system-generated payslip. Payslip is confidential.',
    'date': 'Date',
    'description': 'Description',
    'amount': 'Amount',
  };

  static pw.Document _buildPdf(Map<String, dynamic> payslip, int year, int month, {String lang = 'en'}) {
    final pdf = pw.Document();
    final monthName = DateFormat('MMMM yyyy').format(DateTime(year, month));
    final s = _l(lang);

    // Extract data - All individual components
    final basicSalary = _n(payslip['basic_salary']);
    final transportAllowance = _n(payslip['transport_allowance']);
    final mealAllowance = _n(payslip['meal_allowance']);
    final phoneAllowance = _n(payslip['phone_allowance']);
    final housingAllowance = _n(payslip['housing_allowance']);
    final positionAllowance = _n(payslip['position_allowance']);
    final otherAllowance = _n(payslip['other_allowance']);
    final totalAllowances = _n(payslip['total_allowances']);
    final otHours = _n(payslip['ot_hours']);
    final otAmount = _n(payslip['ot_amount']);
    final attendanceBonus = _n(payslip['attendance_bonus']);
    final performanceBonus = _n(payslip['performance_bonus']);
    final incentive = _n(payslip['incentive']);
    final commission = _n(payslip['commission']);
    final bonus = _n(payslip['bonus']);
    final otherEarnings = _n(payslip['other_earnings']);
    final grossSalary = _n(payslip['gross_salary']);
    final ssbAmount = _n(payslip['ssb_amount']);
    final taxAmount = _n(payslip['tax_amount']);
    final advanceDeduction = _n(payslip['advance_deduction']);
    final absentDeduction = _n(payslip['absent_deduction']);
    final unpaidLeaveDeduction = _n(payslip['unpaid_leave_deduction']);
    final lateDeduction = _n(payslip['late_deduction']);
    final loanDeduction = _n(payslip['loan_deduction']);
    final insuranceDeduction = _n(payslip['insurance_deduction']);
    final uniformDeduction = _n(payslip['uniform_deduction']);
    final otherDeductions = _n(payslip['other_deductions']);
    final totalDeductions = _n(payslip['total_deductions']);
    final netSalary = _n(payslip['net_salary']);
    final daysPresent = payslip['days_present'] ?? 0;
    final daysAbsent = payslip['days_absent'] ?? 0;
    final daysLate = payslip['days_late'] ?? 0;
    final daysOnLeave = payslip['days_on_leave'] ?? 0;
    final totalWorkingDays = payslip['total_working_days'] ?? 0;
    final status = payslip['status'] ?? 'calculated';

    // Employee info
    final emp = payslip['employee'] is Map ? payslip['employee'] as Map : {};
    final empName = '${emp['first_name'] ?? ''} ${emp['last_name'] ?? ''}'.trim();
    final empNameMm = emp['name_mm'] ?? '';
    final empCode = emp['employee_code'] ?? '';
    final empPhone = emp['phone'] ?? '';
    final empNrc = emp['nrc_number'] ?? '';
    final empSsb = emp['ssb_number'] ?? '';
    final bankName = emp['bank_name'] ?? '';
    final bankAccount = emp['bank_account_number'] ?? '';
    final dept = emp['department'] is Map ? emp['department']['name'] ?? '' : '';
    final position = emp['position'] is Map ? emp['position']['title'] ?? '' : '';

    // Company info
    final company = emp['company'] is Map ? emp['company'] as Map : {};
    final companyName = company['name'] ?? 'Easy HR';
    final companyNameMm = company['name_mm'] ?? '';
    final companyAddress = company['address'] ?? '';
    final companyPhone = company['phone'] ?? '';
    final companyEmail = company['email'] ?? '';

    final accent = PdfColor.fromHex('#2563EB');
    final green = PdfColor.fromHex('#10B981');
    final red = PdfColor.fromHex('#EF4444');
    final lightBg = PdfColor.fromHex('#F8FAFC');
    final borderColor = PdfColor.fromHex('#E2E8F0');

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // ═══════════ HEADER ═══════════
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.symmetric(horizontal: 20, vertical: 16),
                decoration: pw.BoxDecoration(
                  color: accent,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Row(
                  children: [
                    pw.Expanded(
                      child: pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text(companyName.toString(),
                              style: pw.TextStyle(color: PdfColors.white, fontSize: 18, fontWeight: pw.FontWeight.bold)),
                          if (companyNameMm.toString().isNotEmpty)
                            pw.Text(companyNameMm.toString(), style: const pw.TextStyle(color: PdfColors.white, fontSize: 10)),
                          if (companyAddress.toString().isNotEmpty)
                            pw.Text(companyAddress.toString(), style: const pw.TextStyle(color: PdfColors.white, fontSize: 9)),
                          if (companyPhone.toString().isNotEmpty || companyEmail.toString().isNotEmpty)
                            pw.Text('${companyPhone.toString().isNotEmpty ? companyPhone : ''}${companyEmail.toString().isNotEmpty ? ' | $companyEmail' : ''}',
                                style: const pw.TextStyle(color: PdfColors.white, fontSize: 9)),
                        ],
                      ),
                    ),
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.end,
                      children: [
                        pw.Text(s['payslip']!, style: pw.TextStyle(color: PdfColors.white, fontSize: 22, fontWeight: pw.FontWeight.bold)),
                        pw.SizedBox(height: 4),
                        pw.Container(
                          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                          decoration: pw.BoxDecoration(
                            color: PdfColors.white,
                            borderRadius: pw.BorderRadius.circular(4),
                          ),
                          child: pw.Text(monthName, style: pw.TextStyle(color: accent, fontSize: 11, fontWeight: pw.FontWeight.bold)),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 16),

              // ═══════════ EMPLOYEE INFO + PAYROLL INFO ═══════════
              pw.Container(
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: borderColor),
                  borderRadius: pw.BorderRadius.circular(6),
                ),
                child: pw.Row(
                  children: [
                    pw.Expanded(
                      child: pw.Container(
                        padding: const pw.EdgeInsets.all(12),
                        child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Container(
                              padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                              color: lightBg,
                              child: pw.Text(s['employee_info']!, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: accent)),
                            ),
                            pw.SizedBox(height: 6),
                            _infoRow(s['name']!, empNameMm.toString().isNotEmpty ? '$empName ($empNameMm)' : (empName.isEmpty ? 'N/A' : empName)),
                            _infoRow(s['emp_code']!, empCode.toString().isEmpty ? '-' : empCode.toString()),
                            _infoRow(s['department']!, dept.toString().isEmpty ? '-' : dept.toString()),
                            _infoRow(s['position']!, position.toString().isEmpty ? '-' : position.toString()),
                            _infoRow(s['phone']!, empPhone.toString().isEmpty ? '-' : empPhone.toString()),
                          ],
                        ),
                      ),
                    ),
                    pw.Container(width: 1, height: 110, color: borderColor),
                    pw.Expanded(
                      child: pw.Container(
                        padding: const pw.EdgeInsets.all(12),
                        child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Container(
                              padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                              color: lightBg,
                              child: pw.Text(s['payroll_info']!, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: accent)),
                            ),
                            pw.SizedBox(height: 6),
                            _infoRow(s['pay_period']!, monthName),
                            _infoRow(s['basic_salary']!, _fmt(basicSalary)),
                            _infoRow(s['nrc']!, empNrc.toString().isEmpty ? '-' : empNrc.toString()),
                            _infoRow(s['bank']!, bankName.toString().isEmpty ? '-' : bankName.toString()),
                            _infoRow(s['bank_acc']!, bankAccount.toString().isEmpty ? '-' : bankAccount.toString()),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 12),

              // ═══════════ ATTENDANCE SUMMARY ═══════════
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 12),
                decoration: pw.BoxDecoration(
                  color: lightBg,
                  border: pw.Border.all(color: borderColor),
                  borderRadius: pw.BorderRadius.circular(6),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                  children: [
                    _attendanceItem(s['working_days']!, '$totalWorkingDays', accent),
                    _attendanceItem(s['present']!, '$daysPresent', green),
                    _attendanceItem(s['absent']!, '$daysAbsent', red),
                    _attendanceItem(s['late']!, '$daysLate', PdfColor.fromHex('#F59E0B')),
                    _attendanceItem(s['on_leave']!, '$daysOnLeave', PdfColor.fromHex('#8B5CF6')),
                  ],
                ),
              ),
              pw.SizedBox(height: 14),

              // ═══════════ EARNINGS TABLE ═══════════
              _sectionHeader(s['earnings']!, s['description']!, s['amount']!, green),
              _earningRow(s['basic_salary']!, basicSalary),
              if (transportAllowance > 0) _earningRow(s['transport']!, transportAllowance),
              if (mealAllowance > 0) _earningRow(s['meal']!, mealAllowance),
              if (phoneAllowance > 0) _earningRow(s['phone_allowance']!, phoneAllowance),
              if (housingAllowance > 0) _earningRow(s['housing']!, housingAllowance),
              if (positionAllowance > 0) _earningRow(s['position_allowance']!, positionAllowance),
              if (otherAllowance > 0) _earningRow(s['other_allowance']!, otherAllowance),
              if (totalAllowances > 0 && transportAllowance == 0 && mealAllowance == 0)
                _earningRow(lang == 'mm' ? 'စုစုပေါင်းစရိတ်' : 'Total Allowances', totalAllowances),
              if (attendanceBonus > 0) _earningRow(s['attendance_bonus']!, attendanceBonus),
              if (otAmount > 0) _earningRow('${s['overtime']!} (${otHours.toStringAsFixed(1)}h)', otAmount),
              if (performanceBonus > 0) _earningRow(s['performance_bonus']!, performanceBonus),
              if (incentive > 0) _earningRow(s['incentive']!, incentive),
              if (commission > 0) _earningRow(s['commission']!, commission),
              if (bonus > 0) _earningRow(payslip['bonus_description']?.toString().isNotEmpty == true ? payslip['bonus_description'].toString() : s['bonus']!, bonus),
              if (otherEarnings > 0) _earningRow(payslip['other_earnings_description']?.toString().isNotEmpty == true ? payslip['other_earnings_description'].toString() : s['other_earnings']!, otherEarnings),
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                color: PdfColor.fromHex('#ECFDF5'),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(s['total_earnings']!, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: green)),
                    pw.Text(_fmt(grossSalary), style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: green)),
                  ],
                ),
              ),
              pw.SizedBox(height: 10),

              // ═══════════ DEDUCTIONS TABLE ═══════════
              _sectionHeader(s['deductions']!, s['description']!, s['amount']!, red),
              if (ssbAmount > 0) _earningRow(s['ssb']!, ssbAmount),
              if (taxAmount > 0) _earningRow(s['income_tax']!, taxAmount),
              if (advanceDeduction > 0) _earningRow(s['advance']!, advanceDeduction),
              if (absentDeduction > 0) _earningRow(s['absent_ded']!, absentDeduction),
              if (unpaidLeaveDeduction > 0) _earningRow(s['unpaid_leave_ded']!, unpaidLeaveDeduction),
              if (lateDeduction > 0) _earningRow(s['late_ded']!, lateDeduction),
              if (loanDeduction > 0) _earningRow(s['loan_ded']!, loanDeduction),
              if (insuranceDeduction > 0) _earningRow(s['insurance_ded']!, insuranceDeduction),
              if (uniformDeduction > 0) _earningRow(s['uniform_ded']!, uniformDeduction),
              if (otherDeductions > 0) _earningRow(payslip['other_deductions_description']?.toString().isNotEmpty == true ? payslip['other_deductions_description'].toString() : s['other_deductions']!, otherDeductions),
              if (totalDeductions == 0) _earningRow('-', 0),
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                color: PdfColor.fromHex('#FEF2F2'),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(s['total_deductions']!, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: red)),
                    pw.Text(_fmt(totalDeductions), style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: red)),
                  ],
                ),
              ),
              pw.SizedBox(height: 14),

              // ═══════════ NET SALARY ═══════════
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(14),
                decoration: pw.BoxDecoration(
                  color: accent,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('${s['net_salary']!} / ${lang == 'mm' ? 'လက်ခံရရှိငွေ' : 'Take Home'}',
                        style: pw.TextStyle(color: PdfColors.white, fontSize: 13, fontWeight: pw.FontWeight.bold)),
                    pw.Text(_fmt(netSalary),
                        style: pw.TextStyle(color: PdfColors.white, fontSize: 18, fontWeight: pw.FontWeight.bold)),
                  ],
                ),
              ),
              pw.Spacer(),

              // ═══════════ FOOTER ═══════════
              pw.Divider(color: borderColor),
              pw.SizedBox(height: 6),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(s['generated_by']!, style: const pw.TextStyle(color: PdfColors.grey, fontSize: 8)),
                  pw.Text('${s['date']!}: ${DateFormat('dd MMM yyyy').format(DateTime.now())}', style: const pw.TextStyle(color: PdfColors.grey, fontSize: 8)),
                ],
              ),
              pw.SizedBox(height: 3),
              pw.Text(s['confidential']!, style: const pw.TextStyle(color: PdfColors.grey, fontSize: 7)),
            ],
          );
        },
      ),
    );

    return pdf;
  }

  static double _n(dynamic v) => v == null ? 0.0 : (v as num).toDouble();

  static pw.Widget _sectionHeader(String title, String descLabel, String amountLabel, PdfColor color) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      color: color,
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(title, style: pw.TextStyle(color: PdfColors.white, fontSize: 10, fontWeight: pw.FontWeight.bold)),
          pw.Row(children: [
            pw.SizedBox(width: 80, child: pw.Text(descLabel, style: const pw.TextStyle(color: PdfColors.white, fontSize: 9), textAlign: pw.TextAlign.right)),
            pw.SizedBox(width: 10),
            pw.SizedBox(width: 80, child: pw.Text(amountLabel, style: const pw.TextStyle(color: PdfColors.white, fontSize: 9), textAlign: pw.TextAlign.right)),
          ]),
        ],
      ),
    );
  }

  static pw.Widget _earningRow(String label, double amount) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey200, width: 0.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(child: pw.Text(label, style: const pw.TextStyle(fontSize: 9))),
          pw.Text(amount > 0 ? _fmt(amount) : '-', style: pw.TextStyle(fontSize: 9, fontWeight: amount > 0 ? pw.FontWeight.bold : pw.FontWeight.normal)),
        ],
      ),
    );
  }

  static pw.Widget _infoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 3),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 80,
            child: pw.Text('$label:', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
          ),
          pw.Expanded(
            child: pw.Text(value, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
          ),
        ],
      ),
    );
  }

  static pw.Widget _attendanceItem(String label, String value, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: color)),
        pw.SizedBox(height: 2),
        pw.Text(label, style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey700)),
      ],
    );
  }

  static String _fmt(double amount) {
    return '${NumberFormat('#,###').format(amount.round())} MMK';
  }
}
