// lib/core/localization/app_strings.dart
// Easy HR Localization - Myanmar & English

class AppStrings {
  static Map<String, String> get(String lang) {
    return lang == 'mm' ? _mm : _en;
  }

  static String t(String key, String lang) {
    final strings = get(lang);
    return strings[key] ?? _en[key] ?? key;
  }

  // ============================================
  // ENGLISH
  // ============================================
  static const Map<String, String> _en = {
    // Navigation
    'nav_home': 'Home',
    'nav_attendance': 'Attendance',
    'nav_payroll': 'Payroll',
    'nav_leave': 'Leave',
    'nav_profile': 'Profile',

    // Home
    'good_morning': 'Good Morning',
    'good_afternoon': 'Good Afternoon',
    'good_evening': 'Good Evening',
    'quick_actions': 'Quick Actions',
    'todays_status': "Today's Status",
    'recent_activity': 'Recent Activity',
    'view_all': 'View All',
    'admin_dashboard': 'Admin Dashboard',
    'admin_dashboard_desc': 'KPI, Reports, Employee Management',
    'check_in': 'Check In',
    'check_out': 'Check Out',
    'hours': 'Hours',
    'leave': 'Leave',
    'calendar': 'Calendar',
    'chat': 'Chat',
    'add_staff': 'Add Staff',
    'employees': 'Employees',
    'reports': 'Reports',
    'announce': 'Announce',
    'payslip': 'Payslip',
    'qr_scan': 'QR Scan',
    'settings': 'Settings',

    // Attendance
    'attendance': 'Attendance',
    'check_in_btn': 'Check In',
    'check_out_btn': 'Check Out',
    'scan_qr': 'Scan QR Code',
    'outside_office': 'Outside office range',
    'move_closer': 'Move closer to your office to check in',
    'recent_history': 'Recent History',
    'present': 'Present',
    'absent': 'Absent',
    'late': 'Late',
    'on_leave': 'On Leave',

    // Leave
    'leave_management': 'Leave Management',
    'my_leaves': 'My Leaves',
    'leave_balance': 'Leave Balance',
    'request_leave': 'Request Leave',
    'leave_type': 'Leave Type',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'reason': 'Reason',
    'submit': 'Submit',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'days_remaining': 'days remaining',
    'casual_leave': 'Casual Leave',
    'annual_leave': 'Annual Leave',
    'sick_leave': 'Sick Leave',
    'public_holiday': 'Public Holiday',

    // Payroll
    'payroll': 'Payroll',
    'overview': 'Overview',
    'salary_setup': 'Salary Setup',
    'my_payslip': 'My Payslip',
    'total_gross': 'Total Gross',
    'total_net': 'Total Net',
    'deductions': 'Deductions',
    'base_salary': 'Base Salary',
    'allowances': 'Allowances',
    'overtime_pay': 'Overtime Pay',
    'gross_salary': 'Gross Salary',
    'net_salary': 'Net Salary',
    'download_pdf': 'Download PDF Payslip',
    'calculate_payroll': 'Calculate Payroll',

    // Profile
    'profile': 'Profile',
    'edit_profile': 'Edit Profile',
    'language': 'Language',
    'dark_mode': 'Dark Mode',
    'notifications': 'Notifications',
    'about': 'About',
    'logout': 'Logout',
    'logout_confirm': 'Are you sure you want to logout?',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'company_settings': 'Company Settings',
    'work_hours': 'Work Hours',
    'leave_settings': 'Leave Settings',

    // Admin
    'admin_actions': 'Admin Actions',
    'add_employee': 'Add Employee',
    'register_new_staff': 'Register new staff',
    'employee_list': 'Employee List',
    'view_manage_staff': 'View & manage all staff',
    'attendance_report': 'Attendance Report',
    'daily_monthly': 'Daily & monthly reports',
    'leave_requests': 'Leave Requests',
    'pending_approvals': 'pending approvals',
    'calculate_send': 'Calculate & send payslips',
    'branches': 'Branches',
    'manage_offices': 'Manage office locations',
    'departments': 'Departments',
    'organize_teams': 'Organize teams',

    // Employee Form
    'personal_info': 'Personal Info',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'phone_number': 'Phone Number',
    'nrc_number': 'NRC Number',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'employee_code': 'Employee Code',
    'auto_generated': 'Auto-generated if empty',
    'work_info': 'Work Info',
    'role': 'Role',
    'employee': 'Employee',
    'hr_manager': 'HR Manager',
    'dept_head': 'Department Head',
    'join_date': 'Join Date',
    'optional': 'Optional',
    'required': 'Required',
    'phone_required': 'Phone number required',
    'invalid_phone': 'Invalid phone number',
    'otp_note': 'Employee will use this phone for OTP login',
    'adding': 'Adding...',
    'employee_added': 'Employee added!',
    'phone_exists': 'Phone number already exists',
    'connection_failed': 'Connection failed',

    // Company Settings
    'work_schedule': 'Work Schedule',
    'work_start': 'Work Start Time',
    'work_end': 'Work End Time',
    'late_threshold': 'Late After (minutes)',
    'working_days': 'Working Days',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'save_settings': 'Save Settings',
    'settings_saved': 'Settings saved!',
    'leave_types_config': 'Leave Types Configuration',
    'days_per_year': 'days/year',
    'add_leave_type': 'Add Leave Type',
    'delete': 'Delete',
    'edit': 'Edit',

    // Payroll PDF
    'preview_pdf': 'Preview PDF',
    'share_pdf': 'Share PDF',
    'no_payslip': 'No payslip available',
    'employee_directory': 'Employee Directory',
  };

  // ============================================
  // MYANMAR (မြန်မာ)
  // ============================================
  static const Map<String, String> _mm = {
    // Navigation
    'nav_home': 'ပင်မ',
    'nav_attendance': 'တက်ရောက်မှု',
    'nav_payroll': 'လစာ',
    'nav_leave': 'ခွင့်',
    'nav_profile': 'ပရိုဖိုင်',

    // Home
    'good_morning': 'မင်္ဂလာနံနက်ခင်းပါ',
    'good_afternoon': 'မင်္ဂလာနေ့လည်ခင်းပါ',
    'good_evening': 'မင်္ဂလာညနေခင်းပါ',
    'quick_actions': 'အမြန်လုပ်ဆောင်ချက်များ',
    'todays_status': 'ယနေ့အခြေအနေ',
    'recent_activity': 'မကြာသေးမီ လှုပ်ရှားမှု',
    'view_all': 'အားလုံးကြည့်ရန်',
    'admin_dashboard': 'Admin ဒိုင်ခွက်ဘုတ်',
    'admin_dashboard_desc': 'KPI၊ အစီရင်ခံစာ၊ ဝန်ထမ်းစီမံခန့်ခွဲမှု',
    'check_in': 'အဝင်',
    'check_out': 'အထွက်',
    'hours': 'နာရီ',
    'leave': 'ခွင့်',
    'calendar': 'ပြက္ခဒိန်',
    'chat': 'ချတ်',
    'add_staff': 'ဝန်ထမ်းထည့်',
    'employees': 'ဝန်ထမ်းများ',
    'reports': 'အစီရင်ခံစာ',
    'announce': 'ကြေညာချက်',
    'payslip': 'လစာဖြတ်ပိုင်း',
    'qr_scan': 'QR စကန်',
    'settings': 'ဆက်တင်',

    // Attendance
    'attendance': 'တက်ရောက်မှု',
    'check_in_btn': 'အလုပ်ဝင်ရန်',
    'check_out_btn': 'အလုပ်ထွက်ရန်',
    'scan_qr': 'QR ကုဒ်စကန်ဖတ်ရန်',
    'outside_office': 'ရုံးနယ်နိမိတ်ပြင်ပ',
    'move_closer': 'အလုပ်ဝင်ရန် ရုံးအနီးသို့ သွားပါ',
    'recent_history': 'မကြာသေးမီ မှတ်တမ်း',
    'present': 'ရှိ',
    'absent': 'ပျက်ကွက်',
    'late': 'နောက်ကျ',
    'on_leave': 'ခွင့်ယူ',

    // Leave
    'leave_management': 'ခွင့်စီမံခန့်ခွဲမှု',
    'my_leaves': 'ကျွန်ုပ်ခွင့်များ',
    'leave_balance': 'ခွင့်လက်ကျန်',
    'request_leave': 'ခွင့်တောင်းရန်',
    'leave_type': 'ခွင့်အမျိုးအစား',
    'start_date': 'စတင်ရက်',
    'end_date': 'ပြီးဆုံးရက်',
    'reason': 'အကြောင်းပြချက်',
    'submit': 'တင်သွင်းရန်',
    'pending': 'စောင့်ဆိုင်းဆဲ',
    'approved': 'ခွင့်ပြုပြီး',
    'rejected': 'ပယ်ချပြီး',
    'days_remaining': 'ရက် ကျန်ရှိ',
    'casual_leave': 'ရိုးရိုးခွင့်',
    'annual_leave': 'နှစ်ပတ်လည်ခွင့်',
    'sick_leave': 'နာမကျန်းခွင့်',
    'public_holiday': 'အများပြည်သူ အားလပ်ရက်',

    // Payroll
    'payroll': 'လစာ',
    'overview': 'ခြုံငုံသုံးသပ်ချက်',
    'salary_setup': 'လစာဖွဲ့စည်းပုံ',
    'my_payslip': 'ကျွန်ုပ်လစာဖြတ်ပိုင်း',
    'total_gross': 'စုစုပေါင်း အကြမ်း',
    'total_net': 'စုစုပေါင်း အသုတ်',
    'deductions': 'နုတ်ယူငွေ',
    'base_salary': 'အခြေခံလစာ',
    'allowances': 'ထောက်ပံ့ငွေ',
    'overtime_pay': 'အချိန်ပိုကြေး',
    'gross_salary': 'လစာအကြမ်း',
    'net_salary': 'လက်ခံရရှိငွေ',
    'download_pdf': 'PDF လစာဖြတ်ပိုင်း ဒေါင်းလုဒ်',
    'calculate_payroll': 'လစာတွက်ချက်ရန်',

    // Profile
    'profile': 'ပရိုဖိုင်',
    'edit_profile': 'ပရိုဖိုင်ပြင်ဆင်ရန်',
    'language': 'ဘာသာစကား',
    'dark_mode': 'အမှောင်မုဒ်',
    'notifications': 'အကြောင်းကြားချက်',
    'about': 'အကြောင်း',
    'logout': 'ထွက်ရန်',
    'logout_confirm': 'ထွက်ရန် သေချာပါသလား?',
    'cancel': 'မလုပ်တော့ပါ',
    'confirm': 'အတည်ပြုရန်',
    'company_settings': 'ကုမ္ပဏီဆက်တင်',
    'work_hours': 'အလုပ်ချိန်',
    'leave_settings': 'ခွင့်ဆက်တင်',

    // Admin
    'admin_actions': 'Admin လုပ်ဆောင်ချက်များ',
    'add_employee': 'ဝန်ထမ်းထည့်ရန်',
    'register_new_staff': 'ဝန်ထမ်းအသစ်မှတ်ပုံတင်ရန်',
    'employee_list': 'ဝန်ထမ်းစာရင်း',
    'view_manage_staff': 'ဝန်ထမ်းများကြည့်ရှု/စီမံရန်',
    'attendance_report': 'တက်ရောက်မှုအစီရင်ခံစာ',
    'daily_monthly': 'နေ့စဥ်/လစဥ် အစီရင်ခံစာ',
    'leave_requests': 'ခွင့်တောင်းစာများ',
    'pending_approvals': 'ခွင့်ပြုရန်ကျန်ရှိ',
    'calculate_send': 'လစာတွက်ချက်/ပို့ရန်',
    'branches': 'ရုံးခွဲများ',
    'manage_offices': 'ရုံးခွဲတည်နေရာစီမံရန်',
    'departments': 'ဌာနများ',
    'organize_teams': 'အဖွဲ့များစီမံရန်',

    // Employee Form
    'personal_info': 'ကိုယ်ရေးအချက်အလက်',
    'first_name': 'အမည်',
    'last_name': 'မျိုးနွယ်အမည်',
    'phone_number': 'ဖုန်းနံပါတ်',
    'nrc_number': 'မှတ်ပုံတင်အမှတ်',
    'gender': 'ကျား/မ',
    'male': 'ကျား',
    'female': 'မ',
    'employee_code': 'ဝန်ထမ်းကုဒ်',
    'auto_generated': 'အလိုအလျောက်ထုတ်ပေးပါမည်',
    'work_info': 'အလုပ်အချက်အလက်',
    'role': 'ရာထူး/အဆင့်',
    'employee': 'ဝန်ထမ်း',
    'hr_manager': 'HR မန်နေဂျာ',
    'dept_head': 'ဌာနမှူး',
    'join_date': 'အလုပ်စဝင်သည့်နေ့',
    'optional': 'ရွေးချယ်စရာ',
    'required': 'ဖြည့်ပါ',
    'phone_required': 'ဖုန်းနံပါတ်ဖြည့်ပါ',
    'invalid_phone': 'ဖုန်းနံပါတ်မှားနေပါသည်',
    'otp_note': 'ဝန်ထမ်းသည် ဤဖုန်းနံပါတ်ဖြင့် OTP login ဝင်ရောက်ပါမည်',
    'adding': 'ထည့်နေပါသည်...',
    'employee_added': 'ဝန်ထမ်းအသစ်ထည့်ပြီးပါပြီ!',
    'phone_exists': 'ဖုန်းနံပါတ် ရှိပြီးသားဖြစ်နိုင်ပါသည်',
    'connection_failed': 'ချိတ်ဆက်မှု မအောင်မြင်ပါ',

    // Company Settings
    'work_schedule': 'အလုပ်အချိန်ဇယား',
    'work_start': 'အလုပ်စချိန်',
    'work_end': 'အလုပ်ဆင်းချိန်',
    'late_threshold': 'နောက်ကျသတ်မှတ်ချက် (မိနစ်)',
    'working_days': 'အလုပ်ရက်များ',
    'monday': 'တနင်္လာ',
    'tuesday': 'အင်္ဂါ',
    'wednesday': 'ဗုဒ္ဓဟူး',
    'thursday': 'ကြာသပတေး',
    'friday': 'သောကြာ',
    'saturday': 'စနေ',
    'sunday': 'တနင်္ဂနွေ',
    'save_settings': 'ဆက်တင်သိမ်းရန်',
    'settings_saved': 'ဆက်တင်သိမ်းပြီး!',
    'leave_types_config': 'ခွင့်အမျိုးအစားသတ်မှတ်ချက်',
    'days_per_year': 'ရက်/နှစ်',
    'add_leave_type': 'ခွင့်အမျိုးအစားထည့်ရန်',
    'delete': 'ဖျက်ရန်',
    'edit': 'ပြင်ဆင်ရန်',

    // Payroll PDF
    'preview_pdf': 'PDF ကြည့်ရန်',
    'share_pdf': 'PDF မျှဝေရန်',
    'no_payslip': 'လစာဖြတ်ပိုင်း မရှိသေးပါ',
    'employee_directory': 'ဝန်ထမ်းလမ်းညွှန်',
  };
}